language: c

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - source armenv.sh
    - export PATH=.env/gcc-arm-none-eabi/bin:$PATH
    - which arm-none-eabi-gcc
    - ls -al `which arm-none-eabi-gcc`

script:
    - source armenv.sh; make

notifications:
    email: false


