language: c

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
    - source armenv.sh

script:
    - source armenv.sh; make

notifications:
    email: false


